import React, { useEffect, useState, useRef } from "react";
import * as signalR from "@microsoft/signalr";
import './App.css';

const DURATION_IN_SECONDS = 30;

function useHighlightOnChange(items, ttl = 900) {
  const [highlights, setHighlights] = useState({});
  const prevRef = useRef([]);

  useEffect(() => {
    const prev = prevRef.current;
    const prevMap = Object.fromEntries((prev || []).map(it => [it.itemId, it.currentHighest]));
    items.forEach(it => {
      const prevVal = prevMap[it.itemId];
      if (prevVal != null && it.currentHighest > prevVal) {
        setHighlights(h => ({ ...h, [it.itemId]: true }));
        setTimeout(() => setHighlights(h => ({ ...h, [it.itemId]: false })), ttl);
      }
    });
    prevRef.current = items;
  }, [items, ttl]);

  return highlights;
}

function AuctionItemCard({ item, highlight }) {
  const percent = Math.max(0, Math.min(100, Math.round((item.timeLeftSeconds / DURATION_IN_SECONDS) * 100)));
  const ended = item.running === false;

  return (
    <div className={`card ${highlight ? "highlight" : ""}`}>
      <div className="cardHeader">
        <div className="title">{item.itemName}</div>
        <div className="status">{ended ? "Closed" : "Live"}</div>
      </div>

      <div className="mainRow">
        <div className="price">
          <div className="label">Highest</div>
          <div className="value">${(item.currentHighest || 0).toFixed(2)}</div>
          <div className="by">by {item.highestBidder || "—"}</div>
        </div>

        <div className="timerCol">
          <div className="timeLeft">{ended ? "0s" : `${item.timeLeftSeconds}s`}</div>
          <div className="progressWrapper" aria-hidden>
            <div className="progressBar" style={{ width: `${percent}%` }} />
          </div>
        </div>
      </div>

      <div className="log">
        {item.lastBids && item.lastBids.length > 0 ? (
          <ul>
            {item.lastBids.slice(0, 4).map((b, i) => (
              <li key={i}>{b}</li>
            ))}
          </ul>
        ) : (
          <div className="muted">No bids yet</div>
        )}
      </div>

      {ended && <div className="endedBadge">Sold: {item.highestBidder} • ${(item.currentHighest || 0).toFixed(2)}</div>}
    </div>
  );
}

export default function App() {
  const [items, setItems] = useState(null);
  const [connection, setConnection] = useState(null);
  const highlights = useHighlightOnChange(items || []);

  useEffect(() => {
    const conn = new signalR.HubConnectionBuilder()
      .withUrl("https://localhost:7129/auctionHub")
      .withAutomaticReconnect()
      .build();

    conn.on("UpdateItems", (data) => {
      const parsed = Array.isArray(data) ? data : (data ?? []);
      setItems(parsed);
    });

    conn.onclose((err) => {
      console.warn("SignalR connection closed", err);
      setConnection(null);
    });

    conn.start()
      .then(() => {
        console.info("SignalR connected");
        setConnection(conn);
      })
      .catch(err => {
        console.error("SignalR start failed", err);
      });

    return () => {
      conn.stop().catch(()=>{});
    };
  }, []);

  return (
    <div className="appRoot">
      <header className="topbar">
        <div className="brand">Auction Simulation Dashboard With SignalR</div>
        <div className="meta">
          <div className="dot" title="real-time">●</div>
          <div className="env">{connection ? "Connected" : "Connecting..."}</div>
        </div>
      </header>

      <main className="container">
        {items === null ? (
          <div className="skeletonGrid">
            {Array.from({ length: 6 }).map((_, i) => <div key={i} className="skeletonCard" />)}
          </div>
        ) : items.length === 0 ? (
          <div className="empty">No auction items available</div>
        ) : (
          <div className="grid">
            {items.map(item => (
              <AuctionItemCard key={item.itemId} item={item} highlight={!!highlights[item.itemId]} />
            ))}
          </div>
        )}
      </main>

      <footer className="footer">
        Simulation only • All bids generated by server
      </footer>
    </div>
  );
}
